# Use Python base image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy the project files to the container
COPY . /app

# Install system dependencies
RUN apt-get update && apt-get install -y curl

# Install Python dependencies
RUN pip install --no-cache-dir streamlit ollama langchain langchain-community qdrant-client bs4 transformers tensorflow tf-keras

# Expose the Streamlit default port
EXPOSE 8501

# Command to run the application
CMD ["streamlit", "run", "app_docker.py", "--server.address", "0.0.0.0"]
